language: php

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpunit --bootstrap vendor/autoload.php --coverage-text Tests/SystemMailer

notifications:
  email:
    - mail@hautzinger.info
